/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.it.academy;

public class App {


    public static void main(String[] args) {
        System.out.println("First commit");
        System.out.println("sum a+b");
    }

    private int a;
    private int b;

    public int getSum(int a, int b) {
        return a + b;

    }

    private int c;
    private int d;

    public int getSumcd(int c, int d) {
        return c + d;

    }

    private int v;
    private int n;

    public int getmult(int v, int n) {
        return v * n;
    }
}
